# Wherever it sees the substring on the left, it suggests the corresponding
# string on the right. 
---
" ACT,": " Australian Capital Territory,"
" AK,": " Alaska,"
" AL,": " Alabama,"
" AR,": " Arkansas,"
" AS,": " American Samoa,"
" AZ,": " Arizona,"
" BC,": " British Columbia,"
" CA,": " California,"
" CO": "Co. or Colorado"
" CT,": " Connecticut,"
" DE,": " Delaware,"
" FL,": " Florida,"
" FM,": " Federated States of Micronesia,"
" GA,": " Georgia,"
" GU,": " Guam,"
" HI,": " Hawaii,"
" IA,": " Iowa,"
" ID,": " Idaho,"
" IL,": " Illinois,"
" IN,": " Indiana,"
" KS,": " Kansas,"
" KY,": " Kentucky,"
" LA,": " Louisiana,"
" MA,": " Massachusetts,"
" MD,": " Maryland,"
" ME,": " Maine,"
" MH,": " Marshall Islands,"
" MI,": " Michigan,"
" MN,": " Minnesota,"
" MO,": " Missouri,"
" MP,": " Northern Mariana Islands,"
" MS,": " Mississippi,"
" MT,": " Montana,"
" NC,": " North Carolina,"
" ND,": " North Dakota,"
" NE,": " Nebraska,"
" NF,": " National Forest,"
" NH,": " New Hampshire,"
" NJ,": " New Jersey,"
" NM,": " New Mexico,"
" NP,": " National Park,"
" NRA,": " National Recreation Area,"
" NSW,": " New South Wales,"
" NV,": " Nevada,"
" NY,": " New York,"
" OH,": " Ohio,"
" OK,": " Oklahoma,"
" OR,": " Oregon,"
" PA,": " Pennsylvania,"
" PR,": " Puerto Rico,"
" PW,": " Palau,"
" QLD,": " Queensland,"
" RI,": " Rhode Island,"
" SC,": " South Carolina,"
" SD,": " South Dakota,"
" SP,": " State Park,"
" TN,": " Tennessee,"
" TX,": " Texas,"
" UT,": " Utah,"
" VA,": " Virginia,"
" VI,": " Virgin Islands,"
" VT,": " Vermont,"
" WA,": " Washington,"
" WI,": " Wisconsin,"
" WV,": " West Virginia,"
" WY,": " Wyoming,"
" area ": "near"
" area,": "near"
"Ave ": "Ave. "
"Ave,": "Ave.,"
"Avenue": "Ave."
"Blvd ": "Blvd. "
"Blvd,": "Blvd.,"
"Boulevard,": "Blvd.,"
"County,": "Co.,"
"Hwy": "Highway"
"Hwy.": "Highway"
"Mt ": "Mount"
"Mt.": "Mount"
"Mtn": "Mountain"
"Mtn.": "Mountain"
"Near ": "near "
"Rd ": "Rd. "
"Rd,": "Rd.,"
"Road,": "Rd.,"
"St ": "St. "
"St,": "St.,"
"Street,": "St.,"
"U.S.": "USA"
"United Kingdom": "England"
"United States": "USA"
"Washington, DC": "Washington DC"
"&": "and"
"‘": "'"
"’": "'"
"“": "\""
"”": "\""
