# Accepted strings for the last word in the location name (first word if scientific).
---
- "Afghanistan"
- "Albania"
- "Algeria"
- "Andorra"
- "Angola"
- "Antarctica"
- "Antigua and Barbuda"
- "Argentina"
- "Armenia"
- "Australia"
- "Austria"
- "Azerbaijan"
- "Bahrain"
- "Bangladesh"
- "Barbados"
- "Belarus"
- "Belgium"
- "Belize"
- "Benin"
- "Bhutan"
- "Bolivia"
- "Bosnia and Herzegovina"
- "Botswana"
- "Brazil"
- "Brunei"
- "Bulgaria"
- "Burkina Faso"
- "Burundi"
- "Cambodia"
- "Cameroon"
- "Canada"
- "Cape Verde"
- "Central African Republic"
- "Chad"
- "Chile"
- "China"
- "Colombia"
- "Comoros"
- "Cook Islands"
- "Costa Rica"
- "Croatia"
- "Cuba"
- "Cyprus"
- "Czech Republic"
- "Democratic Republic of the Congo"
- "Denmark"
- "Djibouti"
- "Dominica"
- "Dominican Republic"
- "Earth"
- "East Timor"
- "Ecuador"
- "Egypt"
- "El Salvador"
- "England"
- "Equatorial Guinea"
- "Eritrea"
- "Estonia"
- "Ethiopia"
- "Europe"
- "Federated States of Micronesia"
- "Fiji"
- "Finland"
- "France"
- "Gabon"
- "Georgia"
- "Germany"
- "Ghana"
- "Greece"
- "Grenada"
- "Guatemala"
- "Guinea"
- "Guinea-Bissau"
- "Guyana"
- "Haiti"
- "Honduras"
- "Hungary"
- "Iceland"
- "India"
- "Indonesia"
- "Iran"
- "Iraq"
- "Ireland"
- "Israel"
- "Italy"
- "Ivory Coast"
- "Jamaica"
- "Japan"
- "Jordan"
- "Kazakhstan"
- "Kenya"
- "Kiribati"
- "Kosovo"
- "Kuwait"
- "Kyrgyzstan"
- "Laos"
- "Latvia"
- "Lebanon"
- "Lesotho"
- "Liberia"
- "Libya"
- "Liechtenstein"
- "Lithuania"
- "Luxembourg"
- "Macedonia"
- "Madagascar"
- "Malawi"
- "Malaysia"
- "Maldives"
- "Mali"
- "Malta"
- "Marshall Islands"
- "Mauritania"
- "Mauritius"
- "Mexico"
- "Moldova"
- "Monaco"
- "Mongolia"
- "Montenegro"
- "Morocco"
- "Mozambique"
- "Myanmar"
- "Namibia"
- "Nauru"
- "Nepal"
- "Netherlands"
- "New Zealand"
- "Nicaragua"
- "Niger"
- "Nigeria"
- "North America"
- "North Korea"
- "Northern Ireland"   # (if we recognize England and Wales and Scotland...)
- "Norway"
- "Oman"
- "Pakistan"
- "Palau"
- "Palestine"
- "Panama"
- "Papua New Guinea"
- "Paraguay"
- "Peru"
- "Philippines"
- "Poland"
- "Portugal"
- "Qatar"
- "Republic of the Congo"
- "Romania"
- "Russia"
- "Rwanda"
- "Saint Kitts and Nevis"
- "Saint Lucia"
- "Saint Vincent and the Grenadines"
- "Samoa"
- "San Marino"
- "Sao Tome and Principe"
- "Saudi Arabia"
- "Scotland"
- "Senegal"
- "Serbia"
- "Seychelles"
- "Sierra Leone"
- "Singapore"
- "Slovakia"
- "Slovenia"
- "Solomon Islands"
- "Somalia"
- "South Africa"
- "South America"
- "South Korea"
- "South Sudan"
- "Spain"
- "Sri Lanka"
- "Sudan"
- "Suriname"
- "Swaziland"
- "Sweden"
- "Switzerland"
- "Syria"
- "Taiwan"
- "Tajikistan"
- "Tanzania"
- "Thailand"
- "The Bahamas"
- "The Gambia"
- "Togo"
- "Tonga"
- "Trinidad and Tobago"
- "Tunisia"
- "Turkey"
- "Turkmenistan"
- "Tuvalu"
- "USA"
- "Uganda"
- "Ukraine"
- "United Arab Emirates"
- "United Kingdom" # Better than British Overseas Territories
- "Unknown"
- "Uruguay"
- "Uzbekistan"
- "Vanuatu"
- "Vatican City"
- "Venezuela"
- "Vietnam"
- "Wales"
- "Yemen"
- "Zambia"
- "Zimbabwe"
