# Supply the Google Maps API keys for your application here.

development:
 localhost:             "AIzaSyDVptnc17hcXKwsxrk4k8W3qY_1oHujr1g"
 localhost.localdomain: "AIzaSyDVptnc17hcXKwsxrk4k8W3qY_1oHujr1g"

test:
 localhost:             "AIzaSyDVptnc17hcXKwsxrk4k8W3qY_1oHujr1g"
 localhost.localdomain: "AIzaSyDVptnc17hcXKwsxrk4k8W3qY_1oHujr1g"

production:
 localhost:             "AIzaSyDVptnc17hcXKwsxrk4k8W3qY_1oHujr1g"
 localhost.localdomain: "AIzaSyDVptnc17hcXKwsxrk4k8W3qY_1oHujr1g"
 mushroomobserver.org:  "AIzaSyDVptnc17hcXKwsxrk4k8W3qY_1oHujr1g"
